#ifndef FACEANOMALY1PLUGIN_GLOBAL_H
#define FACEANOMALY1PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FACEANOMALY1PLUGIN_LIB
# define FACEANOMALY1PLUGIN_EXPORT Q_DECL_EXPORT
#else
# define FACEANOMALY1PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // FACEANOMALY1PLUGIN_GLOBAL_H
